{{- if not .Values.cnpg.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-app.fullname" . }}-dbsecret
type: Opaque
data:
  dbPassword: {{ required "DB password is required" (include "dbPassword" .) | b64enc }}
  dbUser: {{ required "DB user is required" (include "dbUser" .) | b64enc }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-app.fullname" . }}-token
type: Opaque
data:
  staticToken: {{ required "Static Token" (include "staticToken" .) | b64enc }}